### ISSUE TITLE
API : Speechmatics API 

### ISSUE THREAD

**Issue by AncitaAndrade** [AncitaAndrade/Recapify#1]

**Comment by AkashKu95** [comment]
Initial code for Speechmatics API which takes a video as input from local and generate its summary. "Currently hardcoded video path" - change accordingly before running.

**Comment by AkashKu95** [comment]
made speechmatics api to be called dynamically

**Comment by AkashKu95** [comment]
modified speechmatics api function call to align with azure api function call

**Comment by AncitaAndrade** [comment]
Development Done
