### ISSUE TITLE
API :  User Registration and Login

### ISSUE THREAD

**Issue by AncitaAndrade** [AncitaAndrade/Recapify#3]

**Comment by AkashKu95** [comment]
Backbone created for login and sign up pages

**Comment by AkashKu95** [comment]
Added credentials functionality

**Comment by AkashKu95** [comment]
Added working api under 'backend_api' branch handling "username", "password" and "isStudent" field's storage and retrieval from mongoDB successfully.

**Comment by AkashKu95** [comment]
Added 'login' checks through mongoDB

**Comment by AkashKu95** [comment]
entire user object return after login
